"""Unified authentication/authorization exports."""

from app.core.auth.service import (  # noqa: F401
    AuthRepository,
    AuthResult,
    AuthService,
    AuthUser,
    InMemoryAuthRepository,
    PolicyContext,
    SignoffSnapshot,
    SqlAlchemyAuthRepository,
    TokenData,
    TokenResponse,
    UserORMBase,
    UserRecord,
    WorkspaceRole,
    can_export_permit_ready,
    can_invite_architect,
    create_access_token,
    create_refresh_token,
    create_tokens,
    get_current_user,
    get_optional_user,
    requires_signoff,
    verify_token,
    watermark_forced,
    watermark_text,
)

__all__ = [
    "AuthRepository",
    "AuthResult",
    "AuthService",
    "AuthUser",
    "InMemoryAuthRepository",
    "PolicyContext",
    "SignoffSnapshot",
    "SqlAlchemyAuthRepository",
    "TokenData",
    "TokenResponse",
    "UserORMBase",
    "UserRecord",
    "WorkspaceRole",
    "can_export_permit_ready",
    "can_invite_architect",
    "create_access_token",
    "create_refresh_token",
    "create_tokens",
    "get_current_user",
    "get_optional_user",
    "requires_signoff",
    "verify_token",
    "watermark_forced",
    "watermark_text",
]
