[pytest]
addopts = -v --import-mode=importlib
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests unit_tests
norecursedirs = backend .git .venv
asyncio_mode = auto
pythonpath = .
filterwarnings =
    ignore:.*`example` has been deprecated, please use `examples` instead:DeprecationWarning
    ignore:'crypt' is deprecated and slated for removal in Python 3.13:DeprecationWarning
    ignore:datetime.datetime.utcfromtimestamp\(\) is deprecated and scheduled for removal.*:DeprecationWarning
    ignore:datetime.datetime.utcnow\(\) is deprecated and scheduled for removal.*:DeprecationWarning:jose\.jwt
    ignore:'addParseAction' deprecated - use 'add_parse_action':DeprecationWarning
    ignore:'oneOf' deprecated - use 'one_of':DeprecationWarning
    ignore:'setResultsName' deprecated - use 'set_results_name':DeprecationWarning
    ignore:'infixNotation' deprecated - use 'infix_notation':DeprecationWarning
    ignore:'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14.*:DeprecationWarning
    ignore:ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead:DeprecationWarning
    ignore:Support for class-based `config` is deprecated:DeprecationWarning
    ignore:The ``declarative_base\(\)`` function is now available as sqlalchemy.orm.declarative_base:DeprecationWarning
