[pytest]
addopts = -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests unit_tests core/tests jurisdictions
norecursedirs = backend .git .venv
asyncio_mode = strict
pythonpath = .
