export const TID = {
  page: {
    main: 'page-main',
    mission: 'page-mission',
    mappingLive: 'page-mapping-live',
    mappingUpload: 'page-mapping-upload',
    dataUpload: 'page-data-upload',
    securityDashboard: 'page-security-dashboard',
    weakSignal: 'page-weak-signal',
    ticketing: 'page-ticketing',
    settings: 'page-settings',
    complianceDPIA: 'page-compliance-dpia',
    complianceDSAR: 'page-compliance-dsar',
    complianceROPA: 'page-compliance-ropa',
    complianceCBT: 'page-compliance-cbt',
    complianceViolations: 'page-compliance-violations',
  },
  control: {
    floorSelector: 'control-floor-selector',
    timelineBrush: 'control-timeline-brush',
    mapCanvas: 'control-map-canvas',
    ticketRow: 'control-ticket-row',
    clearFilters: 'control-clear-filters',
    uploadInput: 'control-upload-input',
    saveSchema: 'control-save-schema',
    enableGDPR: 'control-enable-gdpr',
  },
} as const
