# Kubernetes CronJob for automated PostgreSQL backups
# Deploy with: kubectl apply -f backup-cron.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: optimal-build
  labels:
    app: optimal-build
    component: backup
spec:
  # Run daily at 2 AM UTC
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 3600  # 1 hour timeout
      template:
        metadata:
          labels:
            app: optimal-build
            component: backup
        spec:
          restartPolicy: OnFailure
          serviceAccountName: backup-service-account
          containers:
            - name: backup
              image: postgres:15-alpine
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  apk add --no-cache aws-cli gzip

                  TIMESTAMP=$(date +%Y%m%d_%H%M%S)
                  BACKUP_FILE="/tmp/${POSTGRES_DB}_${TIMESTAMP}.sql.gz"

                  echo "Starting backup at $(date)"

                  # Perform backup
                  pg_dump \
                    -h "${POSTGRES_HOST}" \
                    -p "${POSTGRES_PORT}" \
                    -U "${POSTGRES_USER}" \
                    -d "${POSTGRES_DB}" \
                    --format=plain \
                    --no-owner \
                    --no-privileges | gzip > "${BACKUP_FILE}"

                  # Verify backup
                  gzip -t "${BACKUP_FILE}"
                  BACKUP_SIZE=$(du -h "${BACKUP_FILE}" | cut -f1)
                  echo "Backup created: ${BACKUP_FILE} (${BACKUP_SIZE})"

                  # Upload to S3
                  aws s3 cp "${BACKUP_FILE}" "s3://${S3_BUCKET}/${S3_PREFIX}/daily/$(basename ${BACKUP_FILE})" \
                    --storage-class STANDARD_IA

                  # Create weekly backup on Sundays
                  if [ $(date +%u) -eq 7 ]; then
                    aws s3 cp "${BACKUP_FILE}" "s3://${S3_BUCKET}/${S3_PREFIX}/weekly/${POSTGRES_DB}_$(date +%Y_W%V).sql.gz" \
                      --storage-class STANDARD_IA
                  fi

                  # Create monthly backup on 1st of month
                  if [ $(date +%d) -eq 01 ]; then
                    aws s3 cp "${BACKUP_FILE}" "s3://${S3_BUCKET}/${S3_PREFIX}/monthly/${POSTGRES_DB}_$(date +%Y%m).sql.gz" \
                      --storage-class GLACIER
                  fi

                  rm -f "${BACKUP_FILE}"
                  echo "Backup completed at $(date)"
              env:
                - name: POSTGRES_HOST
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: host
                - name: POSTGRES_PORT
                  value: "5432"
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: username
                - name: POSTGRES_DB
                  value: building_compliance
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: password
                - name: S3_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: backup-config
                      key: s3-bucket
                - name: S3_PREFIX
                  value: "backups/postgresql"
                - name: AWS_REGION
                  value: "ap-southeast-1"
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "100m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
---
# S3 Lifecycle policy for backup retention (apply via AWS CLI or Terraform)
# aws s3api put-bucket-lifecycle-configuration --bucket YOUR_BUCKET --lifecycle-configuration file://s3-lifecycle.json
#
# s3-lifecycle.json:
# {
#   "Rules": [
#     {
#       "ID": "DailyBackupRetention",
#       "Filter": { "Prefix": "backups/postgresql/daily/" },
#       "Status": "Enabled",
#       "Expiration": { "Days": 7 }
#     },
#     {
#       "ID": "WeeklyBackupRetention",
#       "Filter": { "Prefix": "backups/postgresql/weekly/" },
#       "Status": "Enabled",
#       "Expiration": { "Days": 28 }
#     },
#     {
#       "ID": "MonthlyBackupToGlacier",
#       "Filter": { "Prefix": "backups/postgresql/monthly/" },
#       "Status": "Enabled",
#       "Transitions": [
#         { "Days": 30, "StorageClass": "GLACIER_IR" },
#         { "Days": 90, "StorageClass": "DEEP_ARCHIVE" }
#       ],
#       "Expiration": { "Days": 365 }
#     }
#   ]
# }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: optimal-build
data:
  s3-bucket: "optimal-build-backups"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-service-account
  namespace: optimal-build
  annotations:
    # For EKS with IRSA (IAM Roles for Service Accounts)
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/OptimalBuildBackupRole
